namespace Encamina.Enmarcha.AI.OpenAI.Abstractions;

/// <summary>
/// Represents a completition generated by OpenAI.
/// </summary>
public class Completition
{
    /// <summary>
    /// Gets the text of the generatad completion .
    /// </summary>
    public string Text { get; init; }

    /// <summary>
    /// Gets the respective zero-based positional index for each prompt requested for completion generation.
    /// </summary>
    public int Index { get; init; }

    /// <summary>
    /// Gets the reason that stopped the completion generation.
    /// </summary>
    public string FinishReason { get; init; }
}
