//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encamina.Enmarcha.Data.Cosmos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Encamina.Enmarcha.Data.Cosmos.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Error bulk adding or updating a document!.
        /// </summary>
        internal static string AddOrUpdateBulkException {
            get {
                return ResourceManager.GetString("AddOrUpdateBulkException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Error adding or updating a document!.
        /// </summary>
        internal static string AddOrUpdateEntityException {
            get {
                return ResourceManager.GetString("AddOrUpdateEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting item with Id &apos;{0}&apos; and partition key &apos;{1}&apos;!.
        /// </summary>
        internal static string DeleteItemByIdException {
            get {
                return ResourceManager.GetString("DeleteItemByIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing stored procedure &apos;{0}&apos; and partition key &apos;{1}&apos;!.
        /// </summary>
        internal static string ExecuteStoredProcedureException {
            get {
                return ResourceManager.GetString("ExecuteStoredProcedureException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting document with Id &apos;{0}&apos; and partition key &apos;{1}&apos;!.
        /// </summary>
        internal static string GetByIdException {
            get {
                return ResourceManager.GetString("GetByIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;Database&apos; configuration parameter!.
        /// </summary>
        internal static string MissingDatabaseConfigurationParameterException {
            get {
                return ResourceManager.GetString("MissingDatabaseConfigurationParameterException", resourceCulture);
            }
        }
    }
}
